on:
  workflow_dispatch:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["main"]}

jobs:
  readme-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull

      - uses: actions/setup-python@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          python-version: '3.x'
          architecture: 'x64'

      - name: install requirements
        run: pip install -r requirements.txt

      - name: running script
        run: python auto_update_readme.py

      - name: Push changes
        run: |
          git commit -am "Add changes" || echo "No changes to commit"
          git push || echo "No changes to push"
